//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNWTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class accessory
    {
        public int id { get; set; }
        public string manufacturer { get; set; }
        public string color { get; set; }
        public Nullable<int> product_id { get; set; }
    
        public virtual product product { get; set; }
    }
}
