//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNWTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class accountInfor
    {
        public int id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string identify { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public Nullable<int> account_id { get; set; }
    
        public virtual account account { get; set; }
    }
}
