//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNWTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class billDetail
    {
        public int id { get; set; }
        public string number { get; set; }
        public string money { get; set; }
        public string accept { get; set; }
        public Nullable<int> bill_id { get; set; }
        public Nullable<int> product_id { get; set; }
    
        public virtual bill bill { get; set; }
        public virtual product product { get; set; }
    }
}
